trigger:
- main # Triggers on changes to the `main` branch

variables:
  TF_WORKING_DIR: './' # Terraform files are in the root of the repository
  TF_LIB_DIR: './lib'  # Terraform files are also in the 'lib' directory

pool:
  vmImage: 'selfHostedAgent'

steps:
# Step 1: Install Terraform (latest version managed by Terraform task)
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'
  displayName: Install Terraform

# Step 2: Azure Login using Service Connection
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Tenant' # Use the "Tenant" service connection
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az account show
  displayName: Azure Login

# Step 3: Terraform Init in Root Directory with Debug Logging
- script: |
    export TF_LOG=DEBUG
    export TF_LOG_PATH=$(System.DefaultWorkingDirectory)/terraform-root.log
    terraform init
  workingDirectory: $(TF_WORKING_DIR)
  displayName: Terraform Init (Root Directory with Debug Logging)

# Step 4: Terraform Init in `lib` Directory with Debug Logging
- script: |
    export TF_LOG=DEBUG
    export TF_LOG_PATH=$(System.DefaultWorkingDirectory)/terraform-lib.log
    terraform init
  workingDirectory: $(TF_LIB_DIR)
  displayName: Terraform Init (Lib Directory with Debug Logging)

# Step 5: Terraform Validate in Root Directory
- task: TerraformTaskV4@4
  inputs:
    command: 'validate'
    workingDirectory: $(TF_WORKING_DIR)
    environmentServiceNameAzureRM: 'Tenant'
  displayName: Terraform Validate (Root Directory)

# Step 6: Terraform Plan in Root Directory with Debug Logging
- script: |
    export TF_LOG=DEBUG
    export TF_LOG_PATH=$(System.DefaultWorkingDirectory)/terraform-plan.log
    terraform plan -out=tfplan
  workingDirectory: $(TF_WORKING_DIR)
  displayName: Terraform Plan (Root Directory with Debug Logging)

# Step 7: Terraform Apply in Root Directory
- task: TerraformTaskV4@4
  inputs:
    command: 'apply'
    workingDirectory: $(TF_WORKING_DIR)
    commandOptions: '-auto-approve tfplan'
    environmentServiceNameAzureRM: 'Tenant'
  displayName: Terraform Apply (Root Directory)

# Step 8: Publish Terraform Logs as Artifacts
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(System.DefaultWorkingDirectory)/*.log
    artifactName: terraform-logs
    publishLocation: 'Container'
  displayName: Publish Terraform Logs

