name: Deploy Terraform with OIDC

on:
  workflow_dispatch:
    inputs:
      module:
        description: "Module to deploy"
        required: true
        type: choice
        options:
          - avm-ptn-alz
          - avm-ptn-alz-management
          - avm-ptn-virtualwan
          - avm-ptn-hubnetworking

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Required for OIDC
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure with OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Debug Azure Environment Variables
        run: |
          echo "ARM_CLIENT_ID=$ARM_CLIENT_ID"
          echo "ARM_TENANT_ID=$ARM_TENANT_ID"
          echo "ARM_SUBSCRIPTION_ID=$ARM_SUBSCRIPTION_ID"

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.0

      - name: Terraform Init
        run: |
          cd deployments/${{ github.event.inputs.module }}
          terraform init

      - name: Terraform Plan
        run: |
          cd deployments/${{ github.event.inputs.module }}
          terraform plan -var-file="terraform.tfvars"

      - name: Terraform Apply
        run: |
          cd deployments/${{ github.event.inputs.module }}
          terraform apply -auto-approve -var-file="terraform.tfvars"


